EZ-393 Integrating map, embed, social media and reference cards compo…
srijanone/ezcontent_theme pull request #50
Opened 2020-09-08 11:20 UTC by surbhi90

…nents

2020-09-09 15:40 UTC, kuldev commented
@vaibhavjain-in this looks fine.

2020-09-10 06:55 UTC, vaibhavjain-in requested changes
@surbhi90 Please remove debug statement.

2020-09-10 06:55 UTC, vaibhavjain-in commented on templates/block/block--inline-block--social-media.html.twig
> +    {{ kint(content|keys) }}
Remove Debug statement.

2020-09-11 05:57 UTC, surbhi90 commented on templates/block/block--inline-block--social-media.html.twig
> +    {{ kint(content|keys) }}
Removed the Debug statement

2020-09-11 09:55 UTC, vaibhavjain-in approved these changes
LGTM

2020-09-11 09:57 UTC, merged